using Chronicle.Application.Common.Interfaces;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace Chronicle.Infrastructure.Services.Media;

/// <summary>
/// Writes uploads to a folder on the server and serves them back from a static route.
/// </summary>
/// <remarks>
/// The development default, and a perfectly good production answer when the server has
/// its own persistent volume — which the leading hosting candidate does. It costs
/// nothing, needs no account anywhere, and means the feature is complete and testable
/// before any credentials exist.
/// <para>
/// What it gives up: the media's lifetime is tied to that machine's. Move hosts and the
/// images do not come with you. That is the trade R2 buys out of.
/// </para>
/// </remarks>
public sealed class LocalDiskMediaStorage : IMediaStorage
{
    private readonly LocalDiskOptions _options;
    private readonly IDateTimeProvider _clock;
    private readonly ILogger<LocalDiskMediaStorage> _logger;
    private readonly string _root;

    public LocalDiskMediaStorage(
        IOptions<MediaStorageOptions> options,
        IHostEnvironment environment,
        IDateTimeProvider clock,
        ILogger<LocalDiskMediaStorage> logger)
    {
        ArgumentNullException.ThrowIfNull(options);
        ArgumentNullException.ThrowIfNull(environment);

        _options = options.Value.LocalDisk;
        _clock = clock;
        _logger = logger;

        _root = Path.IsPathRooted(_options.Root)
            ? _options.Root
            : Path.Combine(environment.ContentRootPath, _options.Root);
    }

    public string RootPath => _root;

    public async Task<StoredMedia> UploadAsync(
        Stream content,
        string fileName,
        string contentType,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(content);

        var key = MediaKey.Create(_clock.UtcNow, Path.GetExtension(fileName));
        var path = Resolve(key);

        Directory.CreateDirectory(Path.GetDirectoryName(path)!);

        await using (var file = File.Create(path))
        {
            await content.CopyToAsync(file, cancellationToken).ConfigureAwait(false);
        }

        var size = new FileInfo(path).Length;
        MediaLog.StoredLocally(_logger, key, size);

        return new StoredMedia(
            key,
            $"{_options.PublicPath.TrimEnd('/')}/{key}",
            size,
            contentType);
    }

    public Task DeleteAsync(string storageKey, CancellationToken cancellationToken = default)
    {
        var path = Resolve(storageKey);

        // Already gone is the state the caller wanted. Throwing here would leave a row
        // whose file has vanished permanently undeletable through the CMS.
        if (File.Exists(path))
        {
            File.Delete(path);
        }

        return Task.CompletedTask;
    }

    public MediaStorageInfo Describe() =>
        new("Local disk", _options.QuotaBytes, _root);

    /// <summary>
    /// Turns a key into a path, and refuses anything that escapes the root.
    /// </summary>
    /// <remarks>
    /// Keys are generated by <see cref="MediaKey"/> and cannot contain traversal, so this
    /// should never fire. It exists because "should never" is doing a lot of work in a
    /// method that writes to the filesystem, and the cost of being wrong is arbitrary
    /// file write. The check is on the resolved absolute path, not the string, because
    /// only the resolved path accounts for symlinks and normalisation.
    /// </remarks>
    private string Resolve(string key)
    {
        var combined = Path.GetFullPath(Path.Combine(_root, key));
        var root = Path.GetFullPath(_root);

        if (!combined.StartsWith(root + Path.DirectorySeparatorChar, StringComparison.Ordinal)
            && !string.Equals(combined, root, StringComparison.Ordinal))
        {
            throw new InvalidOperationException($"Media key '{key}' resolves outside the media root.");
        }

        return combined;
    }
}
